# CodeRabbit configuration for TypeScript project
reviews:
  # Use assertive profile for stricter AI reviews
  profile: assertive
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
  tools:
    eslint:
      enabled: true  # Run ESLint as part of the review
  request_changes_workflow: true
  review_status: true
  collapse_walkthrough: false
  path_filters:
    - "src//*.ts"      # All TypeScript files
    - "src//*.tsx"     # All TSX/React component files
    - "!node_modules/"  # Ignore dependencies
    - "!dist/"          # Ignore build output
  path_instructions:
    - path: "src//*.ts"
      instructions: |
        ⚠ Review TypeScript files for adherence to project conventions:
        - Files must be fewer than 100 lines
        - All variables and functions must have explicit types; avoid any
        - Use ternary operators only for single-line conditional assignments
        - Use arrow functions; avoid anonymous functions
        - Use camelCase for variable and function names
        - Define constants for strings and numbers; avoid inline literals
        - Do not use index as object keys; use meaningful names
        - Use single quotes ' for strings
        - Put colors in RGB or RGBA (rgba only if transparent) in a separate colors.ts file

    - path: "src/components//*.tsx"
      instructions: |
        ⚠ Review React component files:
        - Each component must be in a separate file, named after the component
        - Components must have explicit types
        - Do not use React.createClass or React.Component